### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by nickchang** [jmikola/mongoqp#15] opened 2014-10-27 10:19 UTC
RuntimeException: exception: JavaScript execution failed: TypeError: Object -1 has no method 'substr' near '[command].substr(0, 7) === "system.") ' (line 31)

**Comment by sergeygolubev** [comment] 2015-12-13 01:39
I got the same issue

**Comment by jmikola** [comment] 2017-06-21 18:18
This looks like a duplicate of #13 and will be fixed soon.

**Comment by jmikola** [comment] 2017-06-21 18:39
Fixed by https://github.com/jmikola/mongoqp/commit/415de4c99f386fa427408071b12277c567242f37.

**Closed by jmikola** 2017-06-21 18:39 UTC
