### ISSUE TITLE
Failed to download symfony/routing from dist

### ISSUE THREAD

**Issue by ys-roposo** [jmikola/mongoqp#19] opened 2016-02-15 19:44 UTC
the dependency needs to be updated? get this error on install

```
- Installing symfony/routing (v2.2.0)
    Downloading: 0%    Failed to download symfony/routing from dist: The "https://codeload.github.com/symfony/routing/legacy.zip/v2.2.0-RC3" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing symfony/routing (v2.2.0)
    Cloning v2.2.0-RC3
    v2.2.0-RC3 is gone (history was rewritten?)


  [RuntimeException]                                                                  
  Failed to execute git checkout 'v2.2.0-RC3' -- && git reset --hard 'v2.2.0-RC3' --  
  fatal: invalid reference: v2.2.0-RC3   
```

**Comment by jmikola** [comment] 2017-06-21 17:21
This looks like a duplicate of https://github.com/jmikola/mongoqp/issues/18. I should have a fix committed soon.

**Comment by jmikola** [comment] 2017-06-21 18:38
Fixed by https://github.com/jmikola/mongoqp/commit/fcdbc41fba130fbb3693b9ce0f7286643725e2cb.

**Closed by jmikola** 2017-06-21 18:38 UTC
